image: node:latest

cache:
  key: "binaries-cache-$CI_COMMIT_SHA"
  untracked: true
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


stages:
  - dependencies
  - test
  - build
  - build-docker-image
  - deploy

install_dependencies:
  image: node:latest
  stage: dependencies
  script:
    - npm install
  only:
    - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

test-job:
  stage: test
  script:
    - echo "your test here"

build-job:
  image: node:latest
  stage: build
  tags:
    - docker
  script:
    - npm install
  allow_failure: true
  artifacts:
    paths:
      - /home/gitlab-runner/

Build-docker-image:
  image: gitlab/dind
  services:
    - docker:dind
  stage: build-docker-image
  script:
    - docker info
  allow_failure: true

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: http://http://gestiondaarait.als-educ.com/
  script:
    - ssh cp1674563p08@http://http://gestiondaarait.als-educ.com/ "cd var/client/ && git checkout main && git pull origin main && exit"
  only:
    - main
  allow_failure: true